const $=s=>document.querySelector(s);const state={mode:null,pc:null,channel:null,players:new Map(),selfId:crypto.randomUUID(),x:480,y:300,role:'CREW',tasks:[{id:1,name:'Calibrate Reactor',done:false},{id:2,name:'Upload Navigation',done:false},{id:3,name:'Restore Power',done:false}],keys:{},running:false};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function status(t){$('#connectionStatus').textContent=t}
function enc(o){return btoa(unescape(encodeURIComponent(JSON.stringify(o))))}function dec(s){return JSON.parse(decodeURIComponent(escape(atob(s))))}
function addPlayer(p){state.players.set(p.id,p);renderPlayers()}
function renderPlayers(){$('#playerCount').textContent=state.players.size;$('#playerList').innerHTML=[...state.players.values()].map(p=>`<li class="player-row"><span>● ${p.name}</span><span>${p.id===state.selfId?'HOST':''}</span></li>`).join('')}
function send(msg){if(state.channel?.readyState==='open')state.channel.send(JSON.stringify(msg))}
function setupChannel(ch){state.channel=ch;ch.onopen=()=>{status('CONNECTED');toast('Peer connected');send({type:'HELLO',id:state.selfId,name:state.mode==='host'?$('#hostName').value:$('#joinName').value})};ch.onclose=()=>status('DISCONNECTED');ch.onmessage=e=>handle(JSON.parse(e.data))}
function handle(m){if(m.type==='HELLO'){addPlayer({id:m.id,name:m.name});if(state.mode==='host')send({type:'ROSTER',players:[...state.players.values()]})}if(m.type==='ROSTER'){m.players.forEach(addPlayer)}if(m.type==='MOVE'){const p=state.players.get(m.id);if(p){p.x=m.x;p.y=m.y}}if(m.type==='TASK'){const t=state.tasks.find(x=>x.id===m.id);if(t)t.done=true;renderTasks()}if(m.type==='START')startGame()}
function makePC(){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.onicecandidate=()=>{};return pc}
$('#createBtn').onclick=()=>{$('#hostPanel').classList.remove('hidden');$('#joinPanel').classList.add('hidden');$('#launchBtn').classList.remove('hidden');show('#lobbyScreen');state.mode='host';state.players.set(state.selfId,{id:state.selfId,name:$('#hostName').value||'Captain'});renderPlayers();status('HOST MODE')};
$('#joinBtn').onclick=()=>{$('#joinPanel').classList.remove('hidden');$('#hostPanel').classList.add('hidden');$('#launchBtn').classList.add('hidden');show('#lobbyScreen');state.mode='join';status('JOIN MODE')};
$('#backHomeBtn').onclick=()=>show('#homeScreen');
$('#startHostBtn').onclick=async()=>{const pc=makePC();state.pc=pc;setupChannel(pc.createDataChannel('voidcrew',{ordered:true}));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await new Promise(r=>setTimeout(r,1200));$('#offerBox').value=enc({sdp:pc.localDescription});toast('Offer created')};
$('#applyAnswerBtn').onclick=async()=>{try{await state.pc.setRemoteDescription(dec($('#answerBox').value).sdp);toast('Answer applied — connecting')}catch(e){toast('Invalid answer code')}};
$('#createAnswerBtn').onclick=async()=>{try{const pc=makePC();state.pc=pc;pc.ondatachannel=e=>setupChannel(e.channel);await pc.setRemoteDescription(dec($('#joinOfferBox').value).sdp);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await new Promise(r=>setTimeout(r,1200));$('#joinAnswerBox').value=enc({sdp:pc.localDescription});toast('Answer created')}catch(e){toast('Invalid offer code')}};
$('#copyOfferBtn').onclick=()=>navigator.clipboard.writeText($('#offerBox').value).then(()=>toast('Offer copied'));$('#copyAnswerBtn').onclick=()=>navigator.clipboard.writeText($('#joinAnswerBox').value).then(()=>toast('Answer copied'));
$('#launchBtn').onclick=()=>{send({type:'START'});startGame()};
function startGame(){show('#gameScreen');state.running=true;$('#roleBadge').textContent=state.role;renderTasks();requestAnimationFrame(loop);toast('Mission started')}
function renderTasks(){const done=state.tasks.filter(t=>t.done).length;$('#taskText').textContent=`${done} / ${state.tasks.length}`;$('#taskBar').style.width=`${done/state.tasks.length*100}%`;$('#taskList').innerHTML=state.tasks.map(t=>`<div class="task ${t.done?'done':''}">${t.done?'✓':'○'} ${t.name}</div>`).join('')}
addEventListener('keydown',e=>{state.keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')completeTask();if(e.key===' '){e.preventDefault();openMeeting()}});addEventListener('keyup',e=>state.keys[e.key.toLowerCase()]=false);
function completeTask(){const t=state.tasks.find(x=>!x.done);if(t&&Math.hypot(state.x-480,state.y-300)<100){t.done=true;send({type:'TASK',id:t.id});renderTasks();toast('Task completed')}}
function openMeeting(){const m=$('#meetingModal');m.classList.remove('hidden');$('#voteList').innerHTML=[...state.players.values()].map(p=>`<button onclick="vote('${p.id}')">${p.name}</button>`).join('')}
window.vote=id=>{$('#meetingModal').classList.add('hidden');send({type:'VOTE',target:id});toast('Vote submitted')};$('#skipVoteBtn').onclick=()=>$('#meetingModal').classList.add('hidden');
function loop(){if(!state.running)return;let dx=0,dy=0;if(state.keys.w||state.keys.arrowup)dy=-3;if(state.keys.s||state.keys.arrowdown)dy=3;if(state.keys.a||state.keys.arrowleft)dx=-3;if(state.keys.d||state.keys.arrowright)dx=3;state.x=Math.max(25,Math.min(935,state.x+dx));state.y=Math.max(25,Math.min(575,state.y+dy));send({type:'MOVE',id:state.selfId,x:state.x,y:state.y});draw();requestAnimationFrame(loop)}
function draw(){const c=$('#gameCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.fillStyle='#08141d';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#183040';for(let x=0;x<c.width;x+=48){g.beginPath();g.moveTo(x,0);g.lineTo(x,c.height);g.stroke()}for(let y=0;y<c.height;y+=48){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke()}g.fillStyle='#102431';g.fillRect(330,210,300,180);g.fillStyle='#173545';g.fillRect(390,245,180,110);g.fillStyle='#65f6bd';g.beginPath();g.arc(state.x,state.y,13,0,Math.PI*2);g.fill();g.fillStyle='#d9e5ef';g.font='12px system-ui';g.textAlign='center';g.fillText('YOU',state.x,state.y-20);for(const p of state.players.values()){if(p.id===state.selfId)continue;g.fillStyle='#ff6b8a';g.beginPath();g.arc(p.x||150,p.y||150,13,0,Math.PI*2);g.fill();g.fillStyle='#d9e5ef';g.fillText(p.name,p.x||150,(p.y||150)-20)}}
renderPlayers();
