const $=s=>document.querySelector(s);
const TASKS=[{id:1,name:'Calibrate Reactor',x:480,y:300},{id:2,name:'Upload Navigation',x:180,y:150},{id:3,name:'Restore Power',x:780,y:450}];
const state={mode:null,pc:null,channel:null,players:new Map(),selfId:crypto.randomUUID(),x:480,y:300,role:'CREW',tasks:TASKS.map(t=>({...t,done:false})),keys:{},running:false,loopStarted:false,firstMission:true};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2200)}
function status(t){$('#connectionStatus').textContent=t}
function enc(o){return btoa(unescape(encodeURIComponent(JSON.stringify(o))))}function dec(s){return JSON.parse(decodeURIComponent(escape(atob(s))))}
function localPlayer(){return{id:state.selfId,name:state.mode==='host'?($('#hostName').value.trim()||'Captain'):($('#joinName').value.trim()||'Crewmate'),x:state.x,y:state.y}}
function addPlayer(p){if(!p||!p.id)return;const old=state.players.get(p.id)||{};state.players.set(p.id,{...old,...p});renderPlayers()}
function renderPlayers(){$('#playerCount').textContent=state.players.size;$('#crewOnline').textContent=`CREW ${state.players.size}`;$('#waitingHint').textContent=state.players.size<2?'Waiting for crew members…':'Crew connected — ready to launch';$('#playerList').innerHTML=[...state.players.values()].map(p=>`<li class="player-row"><span>● ${p.name||'Crewmate'}</span><span>${p.id===state.selfId?'YOU':'CREW'}</span></li>`).join('')}
function send(msg){if(state.channel?.readyState==='open')state.channel.send(JSON.stringify(msg))}
function setupChannel(ch){state.channel=ch;ch.onopen=()=>{status('CONNECTED');toast('Crew member connected');addPlayer(localPlayer());send({type:'HELLO',...localPlayer()})};ch.onclose=()=>status('DISCONNECTED');ch.onmessage=e=>{try{handle(JSON.parse(e.data))}catch{toast('Received invalid game data')}}}
function handle(m){if(m.type==='HELLO'){addPlayer(m);if(state.mode==='host')send({type:'ROSTER',players:[...state.players.values()]})}else if(m.type==='ROSTER'){m.players.forEach(addPlayer)}else if(m.type==='MOVE'){const p=state.players.get(m.id);if(p){p.x=m.x;p.y=m.y;renderPlayers()}}else if(m.type==='TASK'){const t=state.tasks.find(x=>x.id===m.id);if(t)t.done=true;renderTasks()}else if(m.type==='START'){startGame()}}
function makePC(){return new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]})}
$('#createBtn').onclick=()=>{$('#hostPanel').classList.remove('hidden');$('#joinPanel').classList.add('hidden');$('#launchBtn').classList.remove('hidden');$('#lobbyTitle').textContent='CREATE CREW';show('#lobbyScreen');state.mode='host';addPlayer(localPlayer());status('HOST MODE')};
$('#joinBtn').onclick=()=>{$('#joinPanel').classList.remove('hidden');$('#hostPanel').classList.add('hidden');$('#launchBtn').classList.add('hidden');$('#lobbyTitle').textContent='JOIN CREW';show('#lobbyScreen');state.mode='join';addPlayer(localPlayer());status('JOIN MODE')};
$('#backHomeBtn').onclick=()=>{if(state.channel)state.channel.close();state.running=false;state.channel=null;state.pc=null;show('#homeScreen');status('OFFLINE')};
$('#startHostBtn').onclick=async()=>{try{const pc=makePC();state.pc=pc;setupChannel(pc.createDataChannel('voidcrew',{ordered:true}));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await new Promise(r=>setTimeout(r,900));$('#offerBox').value=enc({sdp:pc.localDescription});toast('Invite code created')}catch(e){toast('Could not create invite')}};
$('#applyAnswerBtn').onclick=async()=>{try{await state.pc.setRemoteDescription(dec($('#answerBox').value.trim()).sdp);toast('Connecting to crew…')}catch(e){toast('Invalid answer code')}};
$('#createAnswerBtn').onclick=async()=>{try{const pc=makePC();state.pc=pc;pc.ondatachannel=e=>setupChannel(e.channel);await pc.setRemoteDescription(dec($('#joinOfferBox').value.trim()).sdp);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await new Promise(r=>setTimeout(r,900));$('#joinAnswerBox').value=enc({sdp:pc.localDescription});toast('Response created — send it to host')}catch(e){toast('Invalid invite code')}};
$('#copyOfferBtn').onclick=()=>navigator.clipboard.writeText($('#offerBox').value).then(()=>toast('Invite copied')).catch(()=>toast('Copy failed'));
$('#copyAnswerBtn').onclick=()=>navigator.clipboard.writeText($('#joinAnswerBox').value).then(()=>toast('Response copied')).catch(()=>toast('Copy failed'));
$('#launchBtn').onclick=()=>{if(state.players.size<1)return;send({type:'START'});startGame()};
function startGame(){show('#gameScreen');state.running=true;$('#roleBadge').textContent=state.role;renderTasks();updateObjective();if(state.firstMission){$('#tutorialModal').classList.remove('hidden');state.firstMission=false}if(!state.loopStarted){state.loopStarted=true;requestAnimationFrame(loop)}toast('Mission started')}
function renderTasks(){const done=state.tasks.filter(t=>t.done).length;$('#taskText').textContent=`${done} / ${state.tasks.length}`;$('#taskBar').style.width=`${done/state.tasks.length*100}%`;$('#taskList').innerHTML=state.tasks.map(t=>`<div class="task ${t.done?'done':''}">${t.done?'✓':'○'} ${t.name}</div>`).join('')}
function updateObjective(){const next=state.tasks.find(t=>!t.done);if(!next){$('#objectiveTitle').textContent='All tasks complete';$('#objectiveHint').textContent='Mission objective achieved!';return}const d=Math.round(Math.hypot(state.x-next.x,state.y-next.y));$('#objectiveTitle').textContent=next.name;$('#objectiveHint').textContent=d<85?'Press E to interact':`Go to the glowing station • ${d}m away`}
function nearestTask(){return state.tasks.filter(t=>!t.done).sort((a,b)=>Math.hypot(state.x-a.x,state.y-a.y)-Math.hypot(state.x-b.x,state.y-b.y))[0]}
function completeTask(){const t=nearestTask();if(t&&Math.hypot(state.x-t.x,state.y-t.y)<85){t.done=true;send({type:'TASK',id:t.id});renderTasks();updateObjective();toast(`✓ ${t.name} complete`);if(state.tasks.every(x=>x.done))toast('🎉 All objectives complete!')}}
function openMeeting(){$('#meetingModal').classList.remove('hidden');$('#voteList').innerHTML=[...state.players.values()].filter(p=>p.id!==state.selfId).map(p=>`<button onclick="vote('${p.id}')">👤 ${p.name||'Crewmate'} <small>VOTE</small></button>`).join('')||'<div class="muted">No other crew members connected.</div>'}
window.vote=id=>{$('#meetingModal').classList.add('hidden');send({type:'VOTE',target:id});toast('Vote submitted')};$('#skipVoteBtn').onclick=()=>{$('#meetingModal').classList.add('hidden');send({type:'VOTE',target:null});toast('Vote skipped')};
$('#tutorialBtn').onclick=()=>$('#tutorialModal').classList.add('hidden');
$('#mapBtn').onclick=()=>$('#mapModal').classList.remove('hidden');$('#closeMapBtn').onclick=()=>$('#mapModal').classList.add('hidden');
addEventListener('keydown',e=>{const k=e.key.toLowerCase();state.keys[k]=true;if(k==='e')completeTask();if(k==='r'||e.key===' ')e.preventDefault(),openMeeting()});addEventListener('keyup',e=>state.keys[e.key.toLowerCase()]=false);
document.querySelectorAll('.mobile-controls button').forEach(btn=>{const k=btn.dataset.key;btn.addEventListener('pointerdown',e=>{e.preventDefault();state.keys[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,()=>state.keys[k]=false))});
function loop(){if(!state.running){state.loopStarted=false;return}let dx=0,dy=0;if(state.keys.w||state.keys.arrowup)dy-=3;if(state.keys.s||state.keys.arrowdown)dy+=3;if(state.keys.a||state.keys.arrowleft)dx-=3;if(state.keys.d||state.keys.arrowright)dx+=3;if(dx&&dy){dx*=.707;dy*=.707}state.x=Math.max(35,Math.min(925,state.x+dx));state.y=Math.max(35,Math.min(565,state.y+dy));const me=state.players.get(state.selfId);if(me){me.x=state.x;me.y=state.y}send({type:'MOVE',id:state.selfId,x:state.x,y:state.y});updateObjective();const t=nearestTask();const near=t&&Math.hypot(state.x-t.x,state.y-t.y)<85;$('#interactionHint').classList.toggle('hidden',!near);draw();requestAnimationFrame(loop)}
function draw(){const c=$('#gameCanvas'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.fillStyle='#071019';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#122735';g.lineWidth=1;for(let x=0;x<c.width;x+=48){g.beginPath();g.moveTo(x,0);g.lineTo(x,c.height);g.stroke()}for(let y=0;y<c.height;y+=48){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke()}
// rooms
[[70,70,220,160,'BRIDGE'],[370,205,220,190,'CENTRAL CORE'],[670,70,220,160,'SECURITY'],[70,390,220,150,'MEDBAY'],[670,390,220,150,'ENGINE']].forEach(([x,y,w,h,n])=>{g.fillStyle='#0c1c27';g.fillRect(x,y,w,h);g.strokeStyle='#1c3a4a';g.strokeRect(x,y,w,h);g.fillStyle='#40586a';g.font='11px system-ui';g.textAlign='center';g.fillText(n,x+w/2,y+20)});
state.tasks.forEach(t=>{if(t.done)return;g.fillStyle='#65f6bd';g.shadowColor='#65f6bd';g.shadowBlur=18;g.beginPath();g.arc(t.x,t.y,7,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='#9feccb';g.font='10px system-ui';g.fillText('TASK',t.x,t.y-14)});
for(const p of state.players.values()){if(p.id===state.selfId)continue;g.fillStyle='#ff718d';g.beginPath();g.arc(p.x||150,p.y||150,13,0,Math.PI*2);g.fill();g.fillStyle='#d9e5ef';g.font='12px system-ui';g.fillText(p.name||'CREW',p.x||150,(p.y||150)-20)}g.fillStyle='#65f6bd';g.beginPath();g.arc(state.x,state.y,14,0,Math.PI*2);g.fill();g.fillStyle='#071019';g.font='bold 9px system-ui';g.fillText('YOU',state.x,state.y+3)}
renderPlayers();
